### ISSUE TITLE
Could you guys give me an example of using json-redux-api with Axios?

### ISSUE THREAD

**Issue by PedroVinicius** [redux-json-api/redux-json-api#156]
Hello, I'm trying to use this library in my project, but I just discovered that in the latest beta, `setEndpointHost` and `setEndpointPath` don't exist anymore. However, reading the source code I have also discovered that there is a method for setting up axios. My question is: how can I do that? What should I do in order to get axios working correctly with `redux-json-api`? Could you give me an example?

**Comment by egeriis** [comment]
You simply want to specify the base URL in the Axios config. That’s the equivalent.

**Comment by PedroVinicius** [comment]
Ok, I wrote that way:

```
store.dispatch(setAxiosConfig({
  baseURL: 'https://my.api/v2',
  headers: {
    'Access-Token': currentUser()
  }
}));
```

Now, how can I fetch an endpoint with its related resources (include)? Do I need to hardcode the include at the end of the path when using `readEndpoint`?

**Comment by egeriis** [comment]
Yeah, `readEndpoint` doesn't care about parsing the URL you're providing. So you can pass any query param through there.

**Comment by dvidsilva** [comment]
Thanks for the hard work @egeriis , using `setAxiosConfig` worked perfect, Any plans for updated documentations and examples? the linked example repo still uses the old way. 

I have some time this week, if no one else is on it I can take a stab at it.

**Comment by egeriis** [comment]
Good to hear @dvidsilva. Unfortunately the example repo is not in my control 😕

**Comment by egeriis** [comment]
The docs _are_ updated. But be sure to check the 2.0 branch.

**Comment by dvidsilva** [comment]
@egeriis no problem. If I create a sample repo for v2 and is good, can it get linked? might be useful for other folks.

**Comment by egeriis** [comment]
@dvidsilva Oh yeah, for sure!

**Comment by PedroVinicius** [comment]
@egeriis, does `setAxiosConfig` accept any config option officially supported by Axios?

**Comment by dvidsilva** [comment]
@egeriis Actually this was faster, I changed the redux-json-api-demo repo to use v2, so people can also have an example of upgrading steps. https://github.com/dvidsilva/redux-json-api-demo 

https://github.com/dvidsilva/redux-json-api-demo/commits/master

**Comment by egeriis** [comment]
@tomharvey Are you open to a PR for these changes?

**Comment by egeriis** [comment]
@PedroVinicius Yes, any config option. They are passed directly.

**Comment by tomharvey** [comment]
@egeriis I'm good with @dvidsilva approach if you guys are. I've yet to upgrade to v2 so I can't really comment on any details, but more than happy to have someone else feed into the guide.

Will be sure to raise a PR with @dvidsilva if I think of anything, while I upgrade to v2, which could help the guide.

**Comment by tomharvey** [comment]
I've also merged @dvidsilva into my repo.

**Comment by tomharvey** [comment]
Time to close the issue?

**Comment by egeriis** [comment]
Good call @tomharvey

**Comment by dvidsilva** [comment]
@egeriis  sorry, the docs are still not updated, the configure still has the old docs, https://github.com/redux-json-api/redux-json-api/blob/v2.0.0/docs/set-up-configure.md 

I can make some time this week and send a PR
